### ISSUE TITLE
Streams not loading video

### ISSUE THREAD

**Issue by saltcod** [plexinc-plugins/FoodNetworkCanada.bundle#5]
Seems all these channels will load the episode names/thumbs, but not the videos. 

New to all this— any idea where I might start debugging?

**Comment by d-bone** [comment]
This still seems to be the case.  Anyone still working on this project?

**Comment by ty2u** [comment]
Looks like someone has fixed this:
https://github.com/jessedyck/FoodNetworkCanada.bundle

**Comment by picard102** [comment]
@ty2u that version doesn't seem to work either.

**Comment by ty2u** [comment]
You're right, it doesn't work. It did though when I posted that. I guess it has to be updated again. It looks like that version was merged into the core plugin which seems to require another update now. Something must have changed again.

**Comment by picard102** [comment]
This still does not work.
